# INFO: GitHub Actions deployment to ECS Fargate cluster
# ? https://docs.github.com/en/actions/how-tos/deploy/deploy-to-third-party-platforms/amazon-elastic-container-service

name: CI-CD ECS Fargate - Demo 1

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 390157243794
  AWS_OIDC_ROLE: iac-aws-oidcRole-app-ecs-demo-1  
  AWS_OIDC_ROLE_PROD: iac-aws-oidcRole-app-ecs-demo-1-prod
  AWS_OIDC_ROLE_STAG: iac-aws-oidcRole-app-ecs-demo-1-stag
  ECR_REPO: 390157243794.dkr.ecr.eu-central-1.amazonaws.com/aws-ecr-nginx
  TASK_FAMILY: ecs-nginx-app1-cicd

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

# INFO: Build & push image to ECR

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t $ECR_REPO:${{ github.sha }} .

      - name: Push image
        run: |
          docker tag $ECR_REPO:${{ github.sha }} $ECR_REPO:${{ github.sha }}
          docker push $ECR_REPO:${{ github.sha }}

      - name: Render task definition
        run: |
          sed "s|$ECR_REPO|$ECR_REPO:${{ github.sha }}|" taskdef.json > taskdef-rendered.json

      - name: Upload taskdef artifact
        uses: actions/upload-artifact@v7
        with:
          name: taskdef
          path: taskdef-rendered.json

# INFO: Deploy - STAG

  deploy-stag:
    name: Deploy to STAG
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: stag
      url: https://your-stag-url.com      

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download taskdef
        uses: actions/download-artifact@v8
        with:
          name: taskdef

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE_STAG }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: taskdef-rendered.json
          service: ecs-nginx-app1-cicd-svc-stag
          cluster: ecs-fargate
          wait-for-service-stability: true
          
# INFO: Deploy - PROD

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-stag
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://your-prod-url.com    

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download taskdef
        uses: actions/download-artifact@v8
        with:
          name: taskdef

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: taskdef-rendered.json
          service: ecs-nginx-app1-cicd-svc-prod
          cluster: ecs-fargate
          wait-for-service-stability: true

# INFO: Cleanup old Task Definitions
#ECS does not auto‑expire or auto‑delete task definition revisions.
# - You may want to roll back instantly
# - ECS needs historical metadata
# - Some revisions may still be used by running tasks
# - AWS treats task definitions as immutable artifacts

  cleanup-task-defs:
    name: Cleanup old Task Definitions
#    needs: deploy-prod
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cleanup old task definitions
        run: |
          FAMILY="${TASK_FAMILY}"
          KEEP=10

          # Get all revisions sorted oldest -> newest
          ARNS=$(aws ecs list-task-definitions \
            --family-prefix $FAMILY \
            --sort ASC \
            --query 'taskDefinitionArns' \
            --output text)

          # Deregister revisions and keep only "KEEP="
          COUNT=0
          for ARN in $ARNS; do
            COUNT=$((COUNT+1))
            if [ $COUNT -le $KEEP ]; then
              echo "Keeping $ARN"
            else
              echo "Deregistering $ARN"
              aws ecs deregister-task-definition --task-definition "$ARN"
            fi
          done

          # Delete all deregistered (INACTIVE) revisions
          if [ ${#TO_DELETE[@]} -gt 0 ]; then
            echo "Deleting INACTIVE task definitions..."
            aws ecs delete-task-definitions \
              --task-definitions "${TO_DELETE[@]}"
          else
            echo "Nothing to delete"
          fi
          
# INFO: Cleanup old ECR images

#  cleanup-ecr:
#    name: Cleanup old ECR images
#    needs: deploy-prod
#    runs-on: ubuntu-latest

#    permissions:
#      id-token: write
#      contents: read

#    steps:
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v6
#        with:
#          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_OIDC_ROLE }}
#          aws-region: ${{ env.AWS_REGION }}

#      - name: Delete old ECR images
#        run: |
#          REPO="${ECR_REPO##*/}"

          # Get all image digests sorted by push time (oldest first)
#          IMAGES=$(aws ecr describe-images \
#            --repository-name "$REPO" \
#            --query 'sort_by(imageDetails,& imagePushedAt)[].imageDigest' \
#            --output text)

#          KEEP=2
#          COUNT=0

#          for DIGEST in $IMAGES; do
#            COUNT=$((COUNT+1))
#            if [ $COUNT -le $KEEP ]; then
#              echo "Keeping image $DIGEST"
#            else
#              echo "Deleting old image $DIGEST"
#              aws ecr batch-delete-image \
#                --repository-name "$REPO" \
#                --image-ids imageDigest="$DIGEST"
#            fi
#          done